# .upptimerc.yml
owner: fortolabs
repo: fortolabs-status

sites:
  # WEB GROUP
  # - name: Login Interface
  #   url: https://auth.youridp.com
  #   group: Web Services
  # - name: Dashboard
  #   url: https://lumodoc.fortolabs.com
  #   group: Web Services

  # API GROUP
  # - name: Authentication API
  #   url: https://api.youridp.com/v1/health
  #   group: API Services
  - name: User API
    url: https://lumodoc.fortolabs.com/api/v1/healthz
    group: API Services

status-website:
  publish: true
  cname: status.fortolabs.com
  name: LumoDoc Status
  introTitle: "All Systems Operational"
  introMessage: "Real-time status of the **LumoDoc** authentication platform. We monitor our global API and Web interfaces."
  navbar:
    - title: Back to Product
      href: https://lumodoc.fortolabs.com
    - title: Documentation
      href: https://fortolabs.com/lumodoc-how-it-works/
