# .upptimerc.yml
owner: fortolabs
repo: fortolabs-status

sites:
  # WEB GROUP
  # - name: Login Interface
  #   url: https://auth.youridp.com
  #   group: Web Services
  # - name: Dashboard
  #   url: https://lumodoc.fortolabs.com
  #   group: Web Services

  # API GROUP
  # - name: Authentication API
  #   url: https://api.youridp.com/v1/health
  #   group: API Services
  - name: User API
    url: https://lumodoc.fortolabs.com/api/v1/healthz
    group: API Services

status-website:
  cname: status.fortolabs.com
  name: LumoDoc Status
  introTitle: "All Systems Operational"
  introMessage: "Real-time status of the **LumoDoc** authentication platform. We monitor our global API and Web interfaces."
  navbar:
    - title: Back to Product
      href: https://lumodoc.fortolabs.com
    - title: Documentation
      href: https://fortolabs.com/lumodoc-how-it-works/

  # CUSTOM CSS
  customCSS: |
    :root {
      --primary-color: #0061ff; /* Dropbox Blue */
    }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
      background-color: #ffffff;
    }
    header {
      border-bottom: 1px solid #e5e5e5;
      padding: 2rem 0;
    }
    .status-header {
      border-radius: 4px;
      padding: 30px;
      margin-top: 20px;
      background-color: #0061ff !important;
      color: white !important;
      font-weight: 700;
      text-align: center;
    }
    /* Grouping style */
    .category-name {
      font-size: 1.4rem;
      font-weight: 800;
      color: #1b2733;
      margin-top: 50px;
      border-bottom: 2px solid #f2f2f2;
      padding-bottom: 10px;
    }
    .site-row {
      border-bottom: 1px solid #f2f2f2;
      padding: 20px 0;
    }
    .site-name {
      font-weight: 500;
      color: #1b2733;
    }